### ISSUE TITLE
Error with flask-file-upload

### ISSUE THREAD

**Issue by kylowrobelek** [joegasewicz/flask-file-upload#99]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/code/app.py", line 12, in <module>
    from galactic_api.views import category_view
  File "/code/galactic_api/views.py", line 8, in <module>
    from .models import Category, file_upload
  File "/code/galactic_api/models.py", line 14, in <module>
    class Category(BasicModel):
  File "/usr/local/lib/python3.8/site-packages/flask_file_upload/model.py", line 50, in __new__
    new_cols_list, filenames_list = _ModelUtils.get_attr_from_model(instance, new_cols, filenames, db)
  File "/usr/local/lib/python3.8/site-packages/flask_file_upload/_model_utils.py", line 123, in get_attr_from_model
    new_cols.append(_ModelUtils.columns_dict(attr, db))
  File "/usr/local/lib/python3.8/site-packages/flask_file_upload/_model_utils.py", line 87, in columns_dict
    return _ModelUtils.create_keys(
  File "/usr/local/lib/python3.8/site-packages/flask_file_upload/_model_utils.py", line 36, in create_keys
    col_dict[key] = fn(key, key)
  File "/usr/local/lib/python3.8/site-packages/flask_file_upload/_model_utils.py", line 86, in create_col
    return db.Column(db.String(str_len), key=key, name=name)
AttributeError: 'NoneType' object has no attribute 'Column'
```

My app.py file looks like this:
```
...
from core.models import db, ma, file_upload
...

def create_app():
    POSTGRES_URL = get_env_variable("POSTGRES_URL")
    POSTGRES_USER = get_env_variable("POSTGRES_USER")
    POSTGRES_PW = get_env_variable("POSTGRES_PW")
    POSTGRES_DB = get_env_variable("POSTGRES_DB")

    DB_URL = 'postgresql+psycopg2://{user}:{pw}@{url}/{db}'.format(
        user=POSTGRES_USER,pw=POSTGRES_PW,url=POSTGRES_URL,db=POSTGRES_DB)


    app = Flask(__name__, static_folder='static')
    app.register_blueprint(admin_teacher_view)
    app.register_blueprint(student_view)
    app.register_blueprint(category_view)
    redis = Redis(host='redis', port=6379)
    app.config['SQLALCHEMY_DATABASE_URI'] = DB_URL
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['SECRET_KEY'] = 'some_secret'
    app.config['JWT_AUTH_USERNAME_KEY'] = 'email'
    app.config['JWT_EXPIRATION_DELTA'] = datetime.timedelta(hours=24)
    app.config["UPLOAD_FOLDER"] = os.path.join(os.path.dirname(
        os.path.realpath(__file__)), "static/uploads")
    app.config["ALLOWED_EXTENSIONS"] = ["jpg", "png", "mov", "mp4", "mpg"]
    app.config["MAX_CONTENT_LENGTH"] = 1000 * 1024

    jwt = JWT(app, authenticate, identity)
    db.init_app(app)
    ma.init_app(app)
    file_upload.init_app(app, db)
    return app


if __name__ == "__main__":
    app = create_app()
    app.run(host="0.0.0.0", debug=True)
```

**Comment by joegasewicz** [comment]
@kylowrobelek thanks for this, this is a bug that has slipped in, will update now and add some tests to make sure this doesn't appear again.
Thanks
Joe
